name: emergent-hamiltonian
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.2
  - scipy=1.15
  - numba=0.65
  - matplotlib=3.10
  - pyyaml
  - openmm=8.5
  - packmol=21.2
  - pytest
  - pytorch>=2.6
  - pytorch-cuda=13.0
